version: '3.8'

services:
  face_recognition:
    build: ./face/src/
    container_name: faceindex
    ports:
      - "8000:8000"  
    environment:
      - REDIS_HOST=172.17.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=RSU_StrongPassword