version: '3.8'

services:
  face_recognition:
    image: fakhryhiz/faceindex:latest
    container_name: faceindex
    ports:
      - "8000:8000"  
    environment:
      - REDIS_HOST=10.20.0.227
      - REDIS_PORT=6379
      - REDIS_PASSWORD=RSU_StrongPassword