# Gunakan base image Python
FROM python:3.11-slim

# Set working directory di dalam container
WORKDIR /app
# Install dependencies untuk opencv
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    gfortran \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy file requirements jika ada
COPY requirements.txt .

# Install dependency
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip
RUN pip install opencv-python insightface
RUN pip install onnxruntime
RUN pip install opencv-contrib-python
# Copy semua file project
COPY . .

# Command menjalankan aplikasi
CMD ["python", "main.py"]
