FROM python:3.9-slim

WORKDIR /app

# COPY requirements.txt .
COPY src/. .

RUN pip install --upgrade pip
# RUN pip install -r requirements.txt
# RUN /bin/sh -c pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y \
        cmake \
        g++ \
        git \
        && rm -rf /var/lib/apt/lists/*
 RUN pip install --no-cache-dir \
        dlib \
        opencv-python \
        face_recognition
# RUN /bin/sh -c pip install dlib
# RUN /bin/sh -c pip install --no-cache-dir face_recognition
RUN /bin/sh -c pip install redis
RUN pip install "fastapi[standard]"
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

EXPOSE 8000

CMD ["fastapi", "dev","main.py", "--host", "0.0.0.0", "--port", "8000"]