
POST  http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
 "username":"fakhry1",
 "UrlImage":"https://api.spairum.my.id/api/cdn/image/1755881802754-514-1668593873958-fakhry.webp",
 "preferences":{
    "name":"fakhry Hizballah1",
    "nik":"098213",
        "nohp":[
         "098622314"
    ]

 }
}
###
### edit refresn nik and name
PUT  http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
 "username":"fakhry1",
 "preferences":{
     "name":"AAAA"
   
 }
}
###

### add nohp
POST http://localhost:3000/api/user/nohp HTTP/1.1
content-type: application/json

{
    "username":"fakhry1",
    "nohp":"09871123"
}
###
POST http://localhost:3000/api/user/biodata 
content-type: application/json

{
    "username":"fakhry2",
    "biodata":{
         "FB" :"asasa"
    }
}
###

GET  http://localhost:3000/api/users?limit=5 HTTP/1.1


### face by URL

GET http://localhost:3000/api/finder/byurl?url=https://media.licdn.com/dms/image/v2/C4E03AQFB_OhySRLxFw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1644685059261?e=1759363200&v=beta&t=gNaKnoXDUp6IP-sHSPBIJfWCG-CqTrvlOmp-1mdrJT0

