FROM python:3.9-slim


# RUN pip install -r requirements.txt
# RUN /bin/sh -c pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y \
cmake \
g++ \
git \
 libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgl1 \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 2. Layer Library Python (Hanya berubah kalau requirements.txt berubah)
COPY requirements.txt .
# RUN /bin/sh -c pip install --no-cache-dir -r requirements.txt

# 3. Layer Aplikasi (Paling sering berubah)
COPY . .


RUN pip install --no-cache-dir --upgrade pip opencv-python insightface scikit-learn numpy onnxruntime redis requests fastapi[standard]
# RUN pip install opencv-python insightface scikit-learn numpy
# RUN pip install onnxruntime
# RUN pip install redis
# RUN pip install requests
# RUN pip install "fastapi[standard]"
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

EXPOSE 8000

# CMD ["fastapi", "run","main.py", "--host", "0.0.0.0", "--port", "8000"]
CMD ["python", "-m", "fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]