FROM python:3.9-slim

WORKDIR /app

# COPY requirements.txt .
COPY . .

RUN pip install --upgrade pip
# RUN pip install -r requirements.txt
# RUN /bin/sh -c pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y \
        cmake \
        g++ \
        git \
        && rm -rf /var/lib/apt/lists/*
# RUN pip install \
#         # --no-cache-dir \
#         # dlib \
#         # opencv-python \
#         face_recognition
# RUN pip install torch torchvision insightface
RUN pip install opencv-python insightface scikit-learn numpy
RUN pip install onnxruntime
RUN pip install redis
RUN pip install requests
RUN pip install "fastapi[standard]"
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

EXPOSE 8000

CMD ["fastapi", "run","main.py", "--host", "0.0.0.0", "--port", "8000"]